### ISSUE TITLE
Can't load dev_mode.rb

### ISSUE THREAD

**Issue by MisteleK** [MisteleK/ProjectAthena#4]
tried to run the program in cmd like this:

    C:\Users\kyle>ruby C:\users\kyle\documents\github\projectathena\projectathena.rb
It spat back this error:

    C:/users/kyle/documents/github/projectathena/projectathena.rb:2:in `load': cannot load such file -- dev_mode.rb (LoadError)
        from C:/users/kyle/documents/github/projectathena/projectathena.rb:2:in `<main>'
Not sure what's causing the error, can't find anything.

**Comment by MisteleK** [comment]
Strange. It gives you that error when you try and run it in CMD.exe but when you run it normally it works fine. Just don't use CMD to run it.

**Comment by Michael-N** [comment]
hmmmm I was able to load dev mode on my pc
